/**
 * DeepVISS OPS
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Metric.
* @enum {}
* @readonly
*/
export default class Metric {
    
        /**
         * value: "euclidean"
         * @const
         */
        "euclidean" = "euclidean";

    
        /**
         * value: "manhattan"
         * @const
         */
        "manhattan" = "manhattan";

    
        /**
         * value: "cosine"
         * @const
         */
        "cosine" = "cosine";

    

    /**
    * Returns a <code>Metric</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Metric} The enum <code>Metric</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

