/**
 * DeepVISS OPS
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Frame from './Frame';
import ObjectOccurrence from './ObjectOccurrence';
import PackedPrefetch from './PackedPrefetch';

/**
 * The PackedSight model module.
 * @module model/PackedSight
 * @version 1.3.0
 */
class PackedSight {
    /**
     * Constructs a new <code>PackedSight</code>.
     * @alias module:model/PackedSight
     */
    constructor() { 
        
        PackedSight.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PackedSight</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PackedSight} obj Optional instance to populate.
     * @return {module:model/PackedSight} The populated <code>PackedSight</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PackedSight();

            if (data.hasOwnProperty('frames')) {
                obj['frames'] = ApiClient.convertToType(data['frames'], [Frame]);
            }
            if (data.hasOwnProperty('occurrences')) {
                obj['occurrences'] = ApiClient.convertToType(data['occurrences'], [ObjectOccurrence]);
            }
            if (data.hasOwnProperty('prefetch')) {
                obj['prefetch'] = PackedPrefetch.constructFromObject(data['prefetch']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Frame>} frames
 */
PackedSight.prototype['frames'] = undefined;

/**
 * @member {Array.<module:model/ObjectOccurrence>} occurrences
 */
PackedSight.prototype['occurrences'] = undefined;

/**
 * @member {module:model/PackedPrefetch} prefetch
 */
PackedSight.prototype['prefetch'] = undefined;






export default PackedSight;

