/**
 * DeepVISS OPS
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectProfile from './ObjectProfile';

/**
 * The PackedPrefetch model module.
 * @module model/PackedPrefetch
 * @version 1.3.0
 */
class PackedPrefetch {
    /**
     * Constructs a new <code>PackedPrefetch</code>.
     * @alias module:model/PackedPrefetch
     */
    constructor() { 
        
        PackedPrefetch.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PackedPrefetch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PackedPrefetch} obj Optional instance to populate.
     * @return {module:model/PackedPrefetch} The populated <code>PackedPrefetch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PackedPrefetch();

            if (data.hasOwnProperty('profiles')) {
                obj['profiles'] = ApiClient.convertToType(data['profiles'], [ObjectProfile]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ObjectProfile>} profiles
 */
PackedPrefetch.prototype['profiles'] = undefined;






export default PackedPrefetch;

