/**
 * DeepVISS OPS
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Point2D model module.
 * @module model/Point2D
 * @version 1.3.0
 */
class Point2D {
    /**
     * Constructs a new <code>Point2D</code>.
     * @alias module:model/Point2D
     * @param x {Number} X-coordinate as integer number of pixels measured from the left to the right.
     * @param y {Number} Y-coordinate as integer number of pixels measured from the top to the bottom.
     */
    constructor(x, y) { 
        
        Point2D.initialize(this, x, y);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, x, y) { 
        obj['x'] = x;
        obj['y'] = y;
    }

    /**
     * Constructs a <code>Point2D</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Point2D} obj Optional instance to populate.
     * @return {module:model/Point2D} The populated <code>Point2D</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Point2D();

            if (data.hasOwnProperty('x')) {
                obj['x'] = ApiClient.convertToType(data['x'], 'Number');
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = ApiClient.convertToType(data['y'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * X-coordinate as integer number of pixels measured from the left to the right.
 * @member {Number} x
 */
Point2D.prototype['x'] = undefined;

/**
 * Y-coordinate as integer number of pixels measured from the top to the bottom.
 * @member {Number} y
 */
Point2D.prototype['y'] = undefined;






export default Point2D;

