/**
 * DeepVISS OPS
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BoundingRectangle from './BoundingRectangle';
import Image from './Image';

/**
 * The ProcessingRequest model module.
 * @module model/ProcessingRequest
 * @version 1.3.0
 */
class ProcessingRequest {
    /**
     * Constructs a new <code>ProcessingRequest</code>.
     * @alias module:model/ProcessingRequest
     */
    constructor() { 
        
        ProcessingRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProcessingRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProcessingRequest} obj Optional instance to populate.
     * @return {module:model/ProcessingRequest} The populated <code>ProcessingRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProcessingRequest();

            if (data.hasOwnProperty('image')) {
                obj['image'] = Image.constructFromObject(data['image']);
            }
            if (data.hasOwnProperty('regionsOfInterest')) {
                obj['regionsOfInterest'] = ApiClient.convertToType(data['regionsOfInterest'], [BoundingRectangle]);
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], {'String': 'String'});
            }
            if (data.hasOwnProperty('frameId')) {
                obj['frameId'] = ApiClient.convertToType(data['frameId'], 'String');
            }
            if (data.hasOwnProperty('frameCounter')) {
                obj['frameCounter'] = ApiClient.convertToType(data['frameCounter'], 'Number');
            }
            if (data.hasOwnProperty('sourceId')) {
                obj['sourceId'] = ApiClient.convertToType(data['sourceId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Image} image
 */
ProcessingRequest.prototype['image'] = undefined;

/**
 * Define any regions of interest, defined by bounding boxes, where the processing should focus.
 * @member {Array.<module:model/BoundingRectangle>} regionsOfInterest
 */
ProcessingRequest.prototype['regionsOfInterest'] = undefined;

/**
 * @member {Object.<String, String>} parameters
 */
ProcessingRequest.prototype['parameters'] = undefined;

/**
 * Alpha-numeric, unique id of frame. You can use (timestamp+sourceId) or sha512(timestamp+sourceId)
 * @member {String} frameId
 */
ProcessingRequest.prototype['frameId'] = undefined;

/**
 * Per-source incremental frame counter
 * @member {Number} frameCounter
 */
ProcessingRequest.prototype['frameCounter'] = undefined;

/**
 * Video source id.
 * @member {String} sourceId
 */
ProcessingRequest.prototype['sourceId'] = undefined;






export default ProcessingRequest;

