/**
 * DeepVISS OPS
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DeepVissOps);
  }
}(this, function(expect, DeepVissOps) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DeepVissOps.SourceStatus();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SourceStatus', function() {
    it('should create an instance of SourceStatus', function() {
      // uncomment below and update the code to test SourceStatus
      //var instane = new DeepVissOps.SourceStatus();
      //expect(instance).to.be.a(DeepVissOps.SourceStatus);
    });

    it('should have the property ingestedFrame (base name: "ingestedFrame")', function() {
      // uncomment below and update the code to test the property ingestedFrame
      //var instane = new DeepVissOps.SourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property processedFrames (base name: "processedFrames")', function() {
      // uncomment below and update the code to test the property processedFrames
      //var instane = new DeepVissOps.SourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property ingestedErrorCount (base name: "ingestedErrorCount")', function() {
      // uncomment below and update the code to test the property ingestedErrorCount
      //var instane = new DeepVissOps.SourceStatus();
      //expect(instance).to.be();
    });

    it('should have the property processedErrorCount (base name: "processedErrorCount")', function() {
      // uncomment below and update the code to test the property processedErrorCount
      //var instane = new DeepVissOps.SourceStatus();
      //expect(instance).to.be();
    });

  });

}));
